
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    restart: always
    env_file:
      - .env
    environment:
      - API_REDIS_HOST=redis
    ports:
      - 8000:8000
    command: [
      "uvicorn", "app:create_app",
      "--host", "0.0.0.0",
      "--port", "8000"
    ]
    depends_on:
      - redis

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: docker/Dockerfile.redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 6379:6379
